/*
    우유, 요거트 = 동시에 구입한 장바구니가 있는가?
    ORDER BY CART_ID ASC;
*/

WITH YOGURT AS (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt'
), MILK AS (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk'
)

SELECT Y.CART_ID
FROM YOGURT Y
INNER JOIN MILK M ON Y.CART_ID = M.CART_ID
GROUP BY Y.CART_ID
ORDER BY CART_ID ASC;