SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE * 30 * (1 - REPLACE(P.DISCOUNT_RATE, '%', '') / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON (C.CAR_TYPE = P.CAR_TYPE AND DURATION_TYPE = '30일 이상')
WHERE C.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
    AND C.CAR_TYPE IN ('세단', 'SUV')
    AND (C.DAILY_FEE * 30 * (1 - REPLACE(P.DISCOUNT_RATE, '%', '') / 100) BETWEEN 500000 AND 1999999)
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC