SELECT U.USER_ID, U.NICKNAME, CONCAT(U.CITY, CONCAT(' ', CONCAT(U.STREET_ADDRESS1, CONCAT(' ', U.STREET_ADDRESS2)))) AS 전체주소, CONCAT(SUBSTRING(TLNO, 1, 3), CONCAT('-', CONCAT(SUBSTRING(TLNO, 4, 4), CONCAT('-', CONCAT(SUBSTRING(TLNO, 8, 4)))))) AS 전화번호
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
GROUP BY U.USER_ID
HAVING COUNT(U.USER_ID) >= 3
ORDER BY U.USER_ID DESC;