-- 식당 ID, 식당 이름, 음식 종류, 즐겨찾기수, 주소, 리뷰 평균 점수
SELECT DISTINCT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS,
(
    SELECT ROUND(AVG(REVIEW_SCORE), 2)
    FROM REST_REVIEW
    WHERE REST_ID = I.REST_ID
) AS SCORE
FROM REST_INFO I INNER JOIN REST_REVIEW R ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE "서울%"
ORDER BY SCORE DESC, I.FAVORITES DESC;