WITH RECURSIVE GENERATIONS AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, GENERATION + 1
    FROM ECOLI_DATA E
    JOIN GENERATIONS G ON E.PARENT_ID = G.ID
)

SELECT COUNT(G.GENERATION) AS COUNT, G.GENERATION
FROM ECOLI_DATA E
JOIN GENERATIONS G ON E.ID = G.ID
WHERE E.ID NOT IN (SELECT DISTINCT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
GROUP BY G.GENERATION
ORDER BY GENERATION;