WITH HEAVY_USERS AS (
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(HOST_ID) > 1
)

SELECT P.ID, P.NAME, P.HOST_ID
FROM PLACES P
INNER JOIN HEAVY_USERS H ON P.HOST_ID = H.HOST_ID
ORDER BY ID;