WITH RENTAL AS (
    SELECT H.HISTORY_ID, C.DAILY_FEE, DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS RENT_DAYS, C.CAR_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)

SELECT HISTORY_ID, FLOOR(R.RENT_DAYS * R.DAILY_FEE * (1 - IFNULL(REPLACE(P.DISCOUNT_RATE, '%', ''), 0) / 100)) FEE
FROM RENTAL R
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON R.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = (
    CASE
        WHEN R.RENT_DAYS >= 90 THEN '90일 이상'
        WHEN R.RENT_DAYS >= 30 THEN '30일 이상'
        WHEN R.RENT_DAYS >= 7 THEN '7일 이상'
    END
)
ORDER BY FEE DESC, R.HISTORY_ID DESC;